/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DAO.UserDAO;
import Model.User;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class frmCadastrarLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form frmCadastrarr
     */
    public frmCadastrarLogin() {
        initComponents();
        
        
    }
    private void Save(){
        String user = tpUser.getText();
        User obj = new User();
        UserDAO dao = new UserDAO();
        obj = dao.BuscarUser(user);
        if(obj.getUser() != null){
            
            obj.setUser(tpUser.getText());
            obj.setNome(tpNome.getText());
            obj.setDataNascimento(ftfData.getText());
            obj.setCartaoSus(ftfSus.getText());
            obj.setCPF(ftfCpf.getText());
            obj.setRG(ftfRg.getText());
            obj.setTelefone(ftfTelefone.getText());
            obj.setMunicipio(tpMunicipio.getText());
            obj.setEndereco(tpEndereco.getText());
            obj.setCEP(ftfCep.getText());
            obj.setSenha(tpSenha.getText());
            obj.setEstado(cbEstado.getSelectedItem().toString());
            obj.setNivelAcesso(cbNivelAcesso.getSelectedItem().toString());
            obj.setFuncao(cbFuncao.getSelectedItem().toString());
            obj.setID(Integer.valueOf(tpCodigo.getText()));
            dao.Editar(obj);
        
        }else{          
            obj.setUser(tpUser.getText());
            obj.setNome(tpNome.getText());
            obj.setDataNascimento(ftfData.getText());
            obj.setCartaoSus(ftfSus.getText());
            obj.setCPF(ftfCpf.getText());
            obj.setRG(ftfRg.getText());
            obj.setTelefone(ftfTelefone.getText());
            obj.setMunicipio(tpMunicipio.getText());
            obj.setEndereco(tpEndereco.getText());
            obj.setCEP(ftfCep.getText());
            obj.setSenha(tpSenha.getText());
            obj.setEstado(cbEstado.getSelectedItem().toString());
            obj.setNivelAcesso(cbNivelAcesso.getSelectedItem().toString());
            obj.setFuncao(cbFuncao.getSelectedItem().toString());
            dao.Salvar(obj);
            tpUser.setText("");
            tpSenha.setText("");
            tpNome.setText("");
            tpMunicipio.setText("");
            tpEndereco.setText("");
            tpConfirma.setText("");
            ftfTelefone.setText("");
            ftfSus.setText("");
            ftfRg.setText("");
            ftfData.setText("");
            ftfCpf.setText("");
            ftfCep.setText("");
            cbEstado.setSelectedIndex(0);
            cbFuncao.setSelectedIndex(0);
            cbNivelAcesso.setSelectedIndex(0);  
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/istockphoto-1432473911-612x612.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        tpUser = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpNome = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        ftfData = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        ftfCpf = new javax.swing.JFormattedTextField();
        ftfRg = new javax.swing.JFormattedTextField();
        ftfSus = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpEndereco = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpMunicipio = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cbNivelAcesso = new javax.swing.JComboBox<>();
        cbFuncao = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tpSenha = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tpConfirma = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtCancelar = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tpCodigo = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        tpUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpUserKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tpUser);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario");

        jScrollPane1.setViewportView(tpNome);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome Completo");

        try {
            ftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDataActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Nascimento");

        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfSus.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.####.####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("CPF:");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("RG:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Cartao SUS");

        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Telefone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfSus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Documentação", jPanel2);

        jScrollPane4.setViewportView(tpEndereco);

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Endereço");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("CEP");

        jScrollPane3.setViewportView(tpMunicipio);

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Municipio");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(31, 42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel3);

        cbNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIVEL DE ACESSO", "ADM", "FATURAMENTO", "FINANCEIRO", "NUTRICIONISTA", "MEDICOS", "FISIOTERAPEUTA", "TI", "RH", "ASSIS.SOCIAL", "ENFERMEIRO", "TECN.ENFERMEIRO", "COMPRAS", "FARMACIA", "BLOCO CIRURGICO", " " }));

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNÇÃO", "OPERADOR DE SISTEMA", "ADMINISTRADOR DE SISTEMA" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cbNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acesso", jPanel4);

        tpSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpSenhaKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tpSenha);

        jScrollPane6.setViewportView(tpConfirma);

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Confirme sua Senha:");

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Senha:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Senha", jPanel5);

        BtCancelar.setBackground(new java.awt.Color(255, 0, 0));
        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9110796_x_icon.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtSalvar.setBackground(new java.awt.Color(102, 255, 102));
        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3994423_checkmark_complete_correct_done_yes_icon.png"))); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");

        tpCodigo.setEditable(false);
        tpCodigo.setMinimumSize(new java.awt.Dimension(100, 60));
        jScrollPane8.setViewportView(tpCodigo);

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setText("Listar Usuarios");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BtExcluir.setBackground(new java.awt.Color(153, 0, 0));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9110796_x_icon.png"))); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btPesquisar)
                        .addGap(43, 43, 43)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ftfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfDataActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        tpUser.setText("");
        tpSenha.setText("");
        tpNome.setText("");
        tpMunicipio.setText("");
        tpEndereco.setText("");
        tpConfirma.setText("");
        ftfSus.setText("");
        ftfTelefone.setText("");
        ftfRg.setText("");
        ftfData.setText("");
        ftfCpf.setText("");
        ftfCep.setText("");
        cbEstado.setSelectedIndex(0);
        cbFuncao.setSelectedIndex(0);
        cbNivelAcesso.setSelectedIndex(0);
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        
        String user = tpUser.getText();
        User obj = new User();
        UserDAO dao = new UserDAO();
        obj = dao.BuscarUser(user);
        if(obj.getUser() != null){
            
            obj.setUser(tpUser.getText());
            obj.setNome(tpNome.getText());
            obj.setDataNascimento(ftfData.getText());
            obj.setCartaoSus(ftfSus.getText());
            obj.setCPF(ftfCpf.getText());
            obj.setRG(ftfRg.getText());
            obj.setTelefone(ftfTelefone.getText());
            obj.setMunicipio(tpMunicipio.getText());
            obj.setEndereco(tpEndereco.getText());
            obj.setCEP(ftfCep.getText());
            obj.setSenha(tpSenha.getText());
            obj.setEstado(cbEstado.getSelectedItem().toString());
            obj.setNivelAcesso(cbNivelAcesso.getSelectedItem().toString());
            obj.setFuncao(cbFuncao.getSelectedItem().toString());
            obj.setID(Integer.valueOf(tpCodigo.getText()));
            dao.Editar(obj);
            tpUser.setText("");
            tpSenha.setText("");
            tpNome.setText("");
            tpMunicipio.setText("");
            tpEndereco.setText("");
            tpConfirma.setText("");
            ftfTelefone.setText("");
            ftfSus.setText("");
            ftfRg.setText("");
            ftfData.setText("");
            ftfCpf.setText("");
            ftfCep.setText("");
            cbEstado.setSelectedIndex(0);
            cbFuncao.setSelectedIndex(0);
            cbNivelAcesso.setSelectedIndex(0); 
        
        }else{          
            obj.setUser(tpUser.getText());
            obj.setNome(tpNome.getText());
            obj.setDataNascimento(ftfData.getText());
            obj.setCartaoSus(ftfSus.getText());
            obj.setCPF(ftfCpf.getText());
            obj.setRG(ftfRg.getText());
            obj.setTelefone(ftfTelefone.getText());
            obj.setMunicipio(tpMunicipio.getText());
            obj.setEndereco(tpEndereco.getText());
            obj.setCEP(ftfCep.getText());
            obj.setSenha(tpSenha.getText());
            obj.setEstado(cbEstado.getSelectedItem().toString());
            obj.setNivelAcesso(cbNivelAcesso.getSelectedItem().toString());
            obj.setFuncao(cbFuncao.getSelectedItem().toString());
            dao.Salvar(obj);
            tpUser.setText("");
            tpSenha.setText("");
            tpNome.setText("");
            tpMunicipio.setText("");
            tpEndereco.setText("");
            tpConfirma.setText("");
            ftfTelefone.setText("");
            ftfSus.setText("");
            ftfRg.setText("");
            ftfData.setText("");
            ftfCpf.setText("");
            ftfCep.setText("");
            cbEstado.setSelectedIndex(0);
            cbFuncao.setSelectedIndex(0);
            cbNivelAcesso.setSelectedIndex(0);  
            }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        String user = tpUser.getText();
        User obj = new User();
        UserDAO dao = new UserDAO();
        obj = dao.BuscarUser(user);
        if(obj.getUser() != null){
            tpCodigo.setText(String.valueOf(obj.getID()));
            tpUser.setText(obj.getUser());
            tpSenha.setText(obj.getSenha());
            tpNome.setText(obj.getNome());
            tpMunicipio.setText(obj.getMunicipio());
            tpEndereco.setText(obj.getEndereco());
            ftfSus.setText(obj.getCartaoSus());
            ftfRg.setText(obj.getRG());
            ftfTelefone.setText(obj.getTelefone());
            ftfData.setText(obj.getDataNascimento());
            ftfCpf.setText(obj.getCPF());
            ftfCep.setText(obj.getCEP());
            cbEstado.setSelectedItem(obj.getEstado());
            cbFuncao.setSelectedItem(obj.getFuncao());
            cbNivelAcesso.setSelectedItem(obj.getNivelAcesso());
            
        
            
        }else{
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ListarUsuarios listar = new ListarUsuarios(this); 
    listar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tpUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpUserKeyReleased
        
    }//GEN-LAST:event_tpUserKeyReleased

    private void tpUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpUserKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String user = tpUser.getText();
        User obj = new User();
        UserDAO dao = new UserDAO();
        obj = dao.BuscarUser(user);
        if(obj.getUser() != null){
            tpCodigo.setText(String.valueOf(obj.getID()));
            tpUser.setText(obj.getUser());
            tpSenha.setText(obj.getSenha());
            tpNome.setText(obj.getNome());
            tpMunicipio.setText(obj.getMunicipio());
            tpEndereco.setText(obj.getEndereco());
            ftfSus.setText(obj.getCartaoSus());
            ftfRg.setText(obj.getRG());
            ftfTelefone.setText(obj.getTelefone());
            ftfData.setText(obj.getDataNascimento());
            ftfCpf.setText(obj.getCPF());
            ftfCep.setText(obj.getCEP());
            cbEstado.setSelectedItem(obj.getEstado());
            cbFuncao.setSelectedItem(obj.getFuncao());
            cbNivelAcesso.setSelectedItem(obj.getNivelAcesso());
            
        
            
        }else{
            JOptionPane.showMessageDialog(null, "Cliente nao encontrado");
        }
            
        }
    }//GEN-LAST:event_tpUserKeyPressed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        User obj = new User();
        obj.setID(Integer.valueOf(tpCodigo.getText()));
        UserDAO dao = new UserDAO();
        dao.Excluir(obj);
        tpUser.setText("");
        tpSenha.setText("");
        tpNome.setText("");
        tpMunicipio.setText("");
        tpEndereco.setText("");
        tpConfirma.setText("");
        ftfTelefone.setText("");
        ftfSus.setText("");
        ftfRg.setText("");
        ftfData.setText("");
        ftfCpf.setText("");
        ftfCep.setText("");
        cbEstado.setSelectedIndex(0);
        cbFuncao.setSelectedIndex(0);
        cbNivelAcesso.setSelectedIndex(0);
        
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void tpSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpSenhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastrarLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastrarLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton btPesquisar;
    protected javax.swing.JComboBox<String> cbEstado;
    protected javax.swing.JComboBox<String> cbFuncao;
    protected javax.swing.JComboBox<String> cbNivelAcesso;
    protected javax.swing.JFormattedTextField ftfCep;
    protected javax.swing.JFormattedTextField ftfCpf;
    protected javax.swing.JFormattedTextField ftfData;
    protected javax.swing.JFormattedTextField ftfRg;
    protected javax.swing.JFormattedTextField ftfSus;
    protected javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JTextPane tpCodigo;
    protected javax.swing.JTextPane tpConfirma;
    protected javax.swing.JTextPane tpEndereco;
    protected javax.swing.JTextPane tpMunicipio;
    protected javax.swing.JTextPane tpNome;
    protected javax.swing.JTextPane tpSenha;
    protected javax.swing.JTextPane tpUser;
    // End of variables declaration//GEN-END:variables
}
