/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import DAO.UserDAO;
import Model.User;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author DP TI
 */
public class frmPrincipal extends javax.swing.JFrame {

    private String usuario;
    
    public frmPrincipal(String usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
    }

    
    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/istockphoto-1432473911-612x612.jpg"));
        Image image = icon.getImage();
        dpnDesk = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NomeUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMovimentos = new javax.swing.JMenu();
        mnuMovimentosUsuarios = new javax.swing.JMenu();
        mnuMovimentosUsuariosCadastro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuMovimentosCadastro = new javax.swing.JMenu();
        mnuMovimentosCadastroInstiruicao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuMovimentosSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuAjudaSobre = new javax.swing.JMenuItem();
        mnuAjudaSuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setExtendedState(6);
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(959, 348));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        dpnDesk.setBackground(new java.awt.Color(153, 153, 153));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5278708_desk_front_furniture_sofa_table_icon.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5929214_avatar_doctor_health_hospital_man_icon.png"))); // NOI18N
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2620498_employee_job_seeker_target_unemployee_icon.png"))); // NOI18N
        jButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4634995_coin_coins_financial_money_icon.png"))); // NOI18N
        jButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6673749_emergency_health_healthcare_hospital_kit_icon.png"))); // NOI18N
        jButton14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recepção Externa");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("P.E.P");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RH");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Controle do Fincnanceiro");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Famacia");

        NomeUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NomeUser.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dpnDeskLayout = new javax.swing.GroupLayout(dpnDesk);
        dpnDesk.setLayout(dpnDeskLayout);
        dpnDeskLayout.setHorizontalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnDeskLayout.createSequentialGroup()
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(925, 925, 925)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(721, 721, 721)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGap(804, 804, 804)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpnDeskLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12)
                        .addGap(93, 93, 93)))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        dpnDeskLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton12, jButton14, jButton3, jButton4, jButton9});

        dpnDeskLayout.setVerticalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpnDeskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dpnDeskLayout.createSequentialGroup()
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))))
                .addGap(32, 32, 32)
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        mnuMovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9074177_users_icon.png"))); // NOI18N
        mnuMovimentos.setText("Movimentos");
        mnuMovimentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        mnuMovimentosUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9074177_users_icon.png"))); // NOI18N
        mnuMovimentosUsuarios.setText("Usuarios");

        mnuMovimentosUsuariosCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1564491_add_create_new_plus_icon.png"))); // NOI18N
        mnuMovimentosUsuariosCadastro.setText("Cadastro ");
        mnuMovimentosUsuariosCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMovimentosUsuariosCadastroMouseClicked(evt);
            }
        });
        mnuMovimentosUsuariosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosUsuariosCadastroActionPerformed(evt);
            }
        });
        mnuMovimentosUsuarios.add(mnuMovimentosUsuariosCadastro);
        mnuMovimentosUsuarios.add(jSeparator2);

        mnuMovimentos.add(mnuMovimentosUsuarios);

        mnuMovimentosCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5925622_college_government_institute_icon.png"))); // NOI18N
        mnuMovimentosCadastro.setText("Cadastro Credenciais");

        mnuMovimentosCadastroInstiruicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5925622_college_government_institute_icon.png"))); // NOI18N
        mnuMovimentosCadastroInstiruicao.setText("Instituição");
        mnuMovimentosCadastroInstiruicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosCadastroInstiruicaoActionPerformed(evt);
            }
        });
        mnuMovimentosCadastro.add(mnuMovimentosCadastroInstiruicao);

        mnuMovimentos.add(mnuMovimentosCadastro);
        mnuMovimentos.add(jSeparator1);

        mnuMovimentosSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1564506_close_exit_logout_power_icon.png"))); // NOI18N
        mnuMovimentosSair.setText("Sair");
        mnuMovimentosSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovimentosSairActionPerformed(evt);
            }
        });
        mnuMovimentos.add(mnuMovimentosSair);

        jMenuBar1.add(mnuMovimentos);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3669466_help_live_ic_icon.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        mnuAjuda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        mnuAjudaSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8207898_about_info_information_help_ui_icon.png"))); // NOI18N
        mnuAjudaSobre.setText("Sobre");
        mnuAjuda.add(mnuAjudaSobre);

        mnuAjudaSuporte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuAjudaSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8324197_ui_essential_app_support_help_icon.png"))); // NOI18N
        mnuAjudaSuporte.setText("Suporte");
        mnuAjuda.add(mnuAjudaSuporte);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dpnDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMovimentosUsuariosCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosUsuariosCadastroActionPerformed
            frmCadastrarLogin u = new frmCadastrarLogin();
            u.setVisible(true);
            
            
        
        
        
    }//GEN-LAST:event_mnuMovimentosUsuariosCadastroActionPerformed

    private void mnuMovimentosUsuariosCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMovimentosUsuariosCadastroMouseClicked
        // TODO add your handling code here:
        
        frmCadastrarLogin u = new frmCadastrarLogin();
            u.setVisible(true);
            
    }//GEN-LAST:event_mnuMovimentosUsuariosCadastroMouseClicked

    private void mnuMovimentosCadastroInstiruicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosCadastroInstiruicaoActionPerformed
        frmInstitucionall i = new frmInstitucionall();
       i.setVisible(true);
    }//GEN-LAST:event_mnuMovimentosCadastroInstiruicaoActionPerformed

    private void mnuMovimentosSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovimentosSairActionPerformed
        frmLogin login = new frmLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_mnuMovimentosSairActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frmRecepcaoExterna externa = new frmRecepcaoExterna();
        externa.setExtendedState(JFrame.MAXIMIZED_BOTH);
        externa.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frmPEP pep = new frmPEP(usuario);
        pep.setExtendedState(JFrame.MAXIMIZED_BOTH);
        pep.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            NomeUser.setText("Bem-vindo, " + usuario);
    }//GEN-LAST:event_formWindowActivated

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        frmFarmacia farma = new frmFarmacia();
        farma.setExtendedState(JFrame.MAXIMIZED_BOTH);
        farma.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        frmRH rh= new frmRH();
        rh.setExtendedState(JFrame.MAXIMIZED_BOTH);
        rh.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        frmFinanceiro finan = new frmFinanceiro();
        finan.setExtendedState(JFrame.MAXIMIZED_BOTH);
        finan.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                frmPrincipal principal = new frmPrincipal("Nome do Usuário");
                principal.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeUser;
    private javax.swing.JPanel dpnDesk;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuAjudaSobre;
    private javax.swing.JMenuItem mnuAjudaSuporte;
    private javax.swing.JMenu mnuMovimentos;
    private javax.swing.JMenu mnuMovimentosCadastro;
    private javax.swing.JMenuItem mnuMovimentosCadastroInstiruicao;
    private javax.swing.JMenuItem mnuMovimentosSair;
    private javax.swing.JMenu mnuMovimentosUsuarios;
    private javax.swing.JMenuItem mnuMovimentosUsuariosCadastro;
    // End of variables declaration//GEN-END:variables
}
