/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import DAO.UserDAO;
import Model.User;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author gabri
 */
public class ListarUsuarios extends javax.swing.JFrame {
    
    
    

    
    
    
    public void Listar(){
     UserDAO dao = new UserDAO();
     List<User> lista = dao.listar();
     DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();
     dados.setNumRows(0);
     for(User u : lista){
         dados.addRow(new Object[]{
         u.getID(),
         u.getUser(),
         u.getNome(),
         u.getDataNascimento(),
         u.getTelefone(),
         u.getCartaoSus(),
         u.getCPF(),
         u.getRG(),
         u.getMunicipio(),
         u.getEndereco(),
         u.getCEP(),
         u.getSenha(),
         u.getEstado(),
         u.getNivelAcesso(),
         u.getFuncao(),
         
     });
     }}
    private frmCadastrarLogin loginForm;
    public ListarUsuarios(frmCadastrarLogin loginForm) {
        this.loginForm = loginForm;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/istockphoto-1432473911-612x612.jpg"));
        Image image = icon.getImage();
        Painel_Guias = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPesquisarNome = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Usuarios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Painel_Guias.setBackground(new java.awt.Color(153, 153, 153));

        txtPesquisarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarNomeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtPesquisarNome);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Nome", "Data Nascimento", "Cartao SUS", "CPF", "RG", "Telefone", "Municipio", "Endereço", "CEP", "Senha", "Estado", "Nivel Acesso", "Função"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela);

        javax.swing.GroupLayout Painel_GuiasLayout = new javax.swing.GroupLayout(Painel_Guias);
        Painel_Guias.setLayout(Painel_GuiasLayout);
        Painel_GuiasLayout.setHorizontalGroup(
            Painel_GuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_GuiasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(1204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_GuiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1516, Short.MAX_VALUE)
                .addContainerGap())
        );
        Painel_GuiasLayout.setVerticalGroup(
            Painel_GuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_GuiasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(Painel_GuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(Painel_GuiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Guias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Guias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
      
        if (loginForm == null) {
        JOptionPane.showMessageDialog(this, "Erro: Tela de cadastro não foi inicializada!");
        return;
    }
        int row = Tabela.getSelectedRow();
     if (row >= 0) { 
         loginForm.tpCodigo.setText(Tabela.getValueAt(row, 0).toString());
         loginForm.tpUser.setText(Tabela.getValueAt(row, 1).toString());
         loginForm.tpNome.setText(Tabela.getValueAt(row, 2).toString());
         loginForm.ftfData.setText(Tabela.getValueAt(row, 3).toString());
         loginForm.ftfTelefone.setText(Tabela.getValueAt(row, 4).toString());
         loginForm.ftfSus.setText(Tabela.getValueAt(row, 5).toString());
         loginForm.ftfCpf.setText(Tabela.getValueAt(row, 6).toString());
         loginForm.ftfRg.setText(Tabela.getValueAt(row, 7).toString());
         loginForm.tpMunicipio.setText(Tabela.getValueAt(row, 8).toString());
         loginForm.tpEndereco.setText(Tabela.getValueAt(row, 9).toString());
         loginForm.ftfCep.setText(Tabela.getValueAt(row, 10).toString());
         loginForm.tpSenha.setText(Tabela.getValueAt(row, 11).toString());
         loginForm.cbEstado.setSelectedItem(Tabela.getValueAt(row, 12).toString());
         loginForm.cbNivelAcesso.setSelectedItem(Tabela.getValueAt(row, 13).toString());
         loginForm.cbFuncao.setSelectedItem(Tabela.getValueAt(row, 14).toString());

         loginForm.setVisible(true); 
     }
    }//GEN-LAST:event_TabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String user = "%"+txtPesquisarNome.getText()+"%";
     UserDAO dao = new UserDAO();
     List<User> lista = dao.Filtrar(user);
     DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();
     dados.setNumRows(0);
     for(User u : lista){
         dados.addRow(new Object[]{
         u.getID(),
         u.getUser(),
         u.getNome(),
         u.getDataNascimento(),
         u.getTelefone(),
         u.getCartaoSus(),
         u.getCPF(),
         u.getRG(),
         u.getMunicipio(),
         u.getEndereco(),
         u.getCEP(),
         u.getSenha(),
         u.getEstado(),
         u.getNivelAcesso(),
         u.getFuncao(),
         
     });
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesquisarNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarNomeKeyReleased
        String user = "%"+txtPesquisarNome.getText()+"%";
     UserDAO dao = new UserDAO();
     List<User> lista = dao.Filtrar(user);
     DefaultTableModel dados = (DefaultTableModel) Tabela.getModel();
     dados.setNumRows(0);
     for(User u : lista){
         dados.addRow(new Object[]{
         u.getID(),
         u.getUser(),
         u.getNome(),
         u.getDataNascimento(),
         u.getTelefone(),
         u.getCartaoSus(),
         u.getCPF(),
         u.getRG(),
         u.getMunicipio(),
         u.getEndereco(),
         u.getCEP(),
         u.getSenha(),
         u.getEstado(),
         u.getNivelAcesso(),
         u.getFuncao(),
         
     });
     }
    }//GEN-LAST:event_txtPesquisarNomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadastrarLogin cadastro = new frmCadastrarLogin(); 
                new ListarUsuarios(cadastro).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Guias;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtPesquisarNome;
    // End of variables declaration//GEN-END:variables
}
